version: '3'
services:
  nats-seed-1:
    image: nats:latest
    ports:
      - 4222:4222
      - 5222:6222
    command: '-c nats-server.conf -D'
  nats-seed-2:
    image: nats:latest
    ports:
      - 4223:4222
      - 6222:6222
    command: '-c nats-server.conf -D'
  nats-2:
    image: nats:latest
    ports:
      - 4224:4222
    command: >
      -c nats-server.conf
      --routes nats-route://ruser:T0pS3cr3t@nats-seed-1:6222,nats-route://ruser:T0pS3cr3t@nats-seed-2:6222
      -D
  nats-3:
    image: nats:latest
    ports:
      - 4225:4222
    command: >
      -c nats-server.conf
      --routes nats-route://ruser:T0pS3cr3t@nats-seed-1:6222,nats-route://ruser:T0pS3cr3t@nats-seed-2:6222
      -D
