apiVersion: nats.io/v1alpha2
kind: NatsCluster
metadata:
  name: ponz-nats-cluster
spec:
  size: 3
  version: "2.0.4"
  natsConfig:
    debug: true
    trace: true
  pod:
    enableMetrics: true
    metricsImage: "synadia/prometheus-nats-exporter"
    metricsImageTag: "0.5.0"
