---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: nats-admin-user
---
apiVersion: nats.io/v1alpha2
kind: NatsServiceRole
metadata:
  name: nats-admin-user
  labels:
    nats_cluster: ponz-nats-cluster-1
spec:
  permissions:
    publish: [">"] # all subjects
    subscribe: [">"] # all subjects
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: nats-app-user
---
apiVersion: nats.io/v1alpha2
kind: NatsServiceRole
metadata:
  name: nats-app-user
  labels:
    nats_cluster: ponz-nats-cluster-1
spec:
  permissions:
    publish: ["app.*.get", "app.*.save", "app.*.delete"] # specific subjects
    subscribe: ["app.>"] # specific subjects
